---
name: "Deployment"

on:
  workflow_dispatch:
  push:
      branches: ["main"]

jobs:
  tst:
    name: tst
    runs-on: "ubuntu-latest"
    uses: robreus/test/.github/workflows/reusable.yaml@main
    with:
      env: tst
    secrets: inherit

  acc:
    name: acc
    needs: tst
    runs-on: "ubuntu-latest"
    uses: robreus/test/.github/workflows/reusable.yaml@main
    with:
      env: acc
    secrets: inherit

  prd:
    name: prd
    needs: acc
    runs-on: "ubuntu-latest"
    uses: robreus/test/.github/workflows/reusable.yaml@main
    with:
      env: prd
    secrets: inherit
