---
name: "Reusable workflow"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Echo env name
        run: echo environment is ${{ inputs.env }}
      - name: Echo secret key
        run: echo ${{ secrets.key }} | sed 's/./& /g'
